### ISSUE TITLE
Very slow execution in WSL using gcm.exe

### ISSUE THREAD

**Issue by pievalentin** [git-ecosystem/git-credential-manager#1234]
I followed the doc to install gcm in wsl (Ubuntu 22.04 LTS)
I used to have a config which was really fast using the Linux install on my previous wsl instance.
Now that I migrated I can't reproduce the same setup so I had to fall back on using the windows .exe

Now every fetch or pull take 25s to interact with Azure DevOps.

Is there a way to install and configure successfully the native linux GCM in wsl?

here is my git config:
```toml
[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
[credential]
        helper = /mnt/c/Program\\ Files/Git/mingw64/bin/git-credential-manager.exe
```
When I tried to use the native linux GCM, I had version `2.0.935`

I would be happy to provide debug logs or config.
